name: ZZU COMMUTE HELPER

on:
    workflow_dispatch:
    schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check
        uses: actions/checkout@v2
    
      - name: Run
        env:
            UID: ${{secrets.UID}}
            UPW: ${{secrets.UPW}}
        run: bash ./script.sh $UID $UPW
        
      #- name: Checkout
       # uses: actions/checkout@v2
        # 安装初始化python
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        # 安装脚本所需的依赖
      - name: 'Install requests'
        run: pip install requests
        # 运行脚本
      - name: 'Working'
        env:	#添加环境变量
          SCKEY: ${{ secrets.SCKEY }}
          SKEY: ${{ secrets.SKEY }}
        run: python ./weather.py
